name: earthspy-dev
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - numpy
  - objectpath
  - pandas
  - rasterio
  - validators
  - sentinelhub >= 3.4
  - pip
  - flake8
  - pytest
  - pytest-lazy-fixture
  - sphinx
  - sphinx_rtd_theme
  - pylint
  - sphinxcontrib-programoutput
  - sphinx-autodoc-typehints
  - pre-commit
  - sphinx-gallery
