name: earthspy
channels:
  - conda-forge/label/cf202003
  - https://conda.software.inl.gov/public
  - defaults
  - conda-forge
dependencies:
  - python=3
  - numpy
  - pandas
  - rasterio
  - sentinelhub >= 3.4
  - pip
