name: earthspy-test
channels:
  - conda-forge/label/cf202003
  - https://conda.software.inl.gov/public
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - rasterio
  - sentinelhub
  - pip
