package:
  name: earthspy
  version: 0.1.0

source:
  git_rev:
  git_url: https://github.com/AdrienWehrle/earthspy.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - earthspy

about:
  home: https://github.com/AdrienWehrle/earthspy
