name: CI
on: [push]

jobs:
  miniconda:
    name: Setup and test
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: true
          
      - shell: bash -l {0}
        run: |
          conda info
          conda list
          
      - name: Install earthspy
        shell: bash -l {0}
        run: |
            pip install -e .
            
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0 
          
      - name: Lint code base
        uses: github/super-linter/slim@v4.9.0
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Run tests
        shell: bash -l {0}
        run: |
          pip install pytest safety
          pytest . || true
          safety check
